In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score



In [3]:
mcd = pd.read_csv('dataset_MCD2.csv')

In [4]:
mcd.head(260)

Calories  CaloriesFat  TransFat  Cholesterol  Sodium  Carbohydrates  \
0         300          120         0          260     750             31   
1         250           70         0           25     770             30   
2         370          200         0           45     780             29   
3         450          250         0          285     860             30   
4         400          210         0           50     880             30   
..        ...          ...       ...          ...     ...            ...   
255       510          150         0           45     280             80   
256       690          200         1           55     380            106   
257       340          100         0           30     190             53   
258       810          290         1           60     400            114   
259       410          150         0           30     200             57   

     Sugars  Protein  Fatty  
0         3       17      0  
1         3       18      0  
2         2       14      0  
3         2       21      0  
4         2       21      0  
..      ...      ...    ...  
255      64       12      0  
256      85       15      1  
257      43        8      0  
258     103       21      1  
259      51       10      0  

[260 rows x 9 columns]

In [5]:
mcd.shape

(260, 9)

In [6]:
mcd['Fatty'].value_counts()

0    230
1     30
Name: Fatty, dtype: int64

In [7]:
Y = mcd['Fatty']
X = mcd.drop (columns='Fatty', axis=1)


In [8]:
print(X)
print(Y)

     Calories  CaloriesFat  TransFat  Cholesterol  Sodium  Carbohydrates  \
0         300          120         0          260     750             31   
1         250           70         0           25     770             30   
2         370          200         0           45     780             29   
3         450          250         0          285     860             30   
4         400          210         0           50     880             30   
..        ...          ...       ...          ...     ...            ...   
255       510          150         0           45     280             80   
256       690          200         1           55     380            106   
257       340          100         0           30     190             53   
258       810          290         1           60     400            114   
259       410          150         0           30     200             57   

     Sugars  Protein  
0         3       17  
1         3       18  
2         2       

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(X)

StandardScaler()

In [11]:
standarized_data = scaler.transform(X)

In [ ]:
print(standarized_data)

[[-0.91410734  0.91050291 -0.87296233  0.69960809 -0.98221664  0.5016002 ]
 [-0.81503461 -1.09829413  1.1455248  -1.4293717   1.01810533  0.26933321]
 [ 2.55343832  0.91050291  1.1455248   0.69960809  1.01810533 -1.35653574]
 ...
 [-0.41874368  0.91050291  1.1455248   0.69960809  1.01810533  0.73386719]
 [-0.12152548  0.91050291 -0.87296233  0.69960809 -0.98221664 -0.42746777]
 [ 1.06734732 -1.09829413  1.1455248   0.69960809  1.01810533  0.73386719]]


In [13]:
X = standarized_data
Y = mcd['Fatty']

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, stratify=Y, random_state=2)

In [15]:
print(X.shape, X_train.shape, X_test.shape)

(260, 8) (208, 8) (52, 8)


In [16]:
classifier = svm.SVC(kernel='linear')

In [17]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [18]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [19]:
print('Akurasi data training adalah =', training_data_accuracy)

Akurasi data training adalah = 1.0


In [20]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [21]:
mcd

Calories  CaloriesFat  TransFat  Cholesterol  Sodium  Carbohydrates  \
0         300          120         0          260     750             31   
1         250           70         0           25     770             30   
2         370          200         0           45     780             29   
3         450          250         0          285     860             30   
4         400          210         0           50     880             30   
..        ...          ...       ...          ...     ...            ...   
255       510          150         0           45     280             80   
256       690          200         1           55     380            106   
257       340          100         0           30     190             53   
258       810          290         1           60     400            114   
259       410          150         0           30     200             57   

     Sugars  Protein  Fatty  
0         3       17      0  
1         3       18      0  
2         2       14      0  
3         2       21      0  
4         2       21      0  
..      ...      ...    ...  
255      64       12      0  
256      85       15      1  
257      43        8      0  
258     103       21      1  
259      51       10      0  

[260 rows x 9 columns]

In [26]:
input_data = (810,290,1,60,400,114,103,21)
input_data_as_numpy_array = np.array(input_data)
input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction [0]== 0):
    print('Makanan berkualitas tinggi lemak')
elif (prediction [0]== 1):
    print('Makanan berkualitas tinggi lemak')


[[ 1.84202322  1.2763782   2.76887462  0.0580668  -0.166257    2.36379194
   2.57040966  0.67182011]]
[1]
Makanan berkualitas tinggi lemak


c:\Users\alifp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
import pickle

In [ ]:
filename = 'mcd.sav'
pickle.dump(classifier, open(filename,'wb'))